### ISSUE TITLE
"Do's and Dont's" should be "Dos and Don'ts"

### ISSUE THREAD

**Issue by daneah** [ithaka/pharos#115]
**Expected behavior**
Proper grammar used for guideline titles

**Actual behavior**
Apostrophes used as plurality, and missing from contractions

**Additional context**
[This](https://github.com/ithaka/pharos/blob/develop/packages/pharos-site/src/components/statics/DosAndDonts.tsx#L29-L53) is the culprit of the incorrect spelling. Note that the spelling is correct [here](https://github.com/ithaka/pharos/blob/develop/packages/pharos-site/src/components/statics/BestPractices.tsx#L30-L61).

**Comment by facelessfool** [comment]
Can I work on this?

**Comment by daneah** [comment]
@facelessfool thanks for your interest—you're welcome to it! I'm assigning you to this issue.

**Comment by facelessfool** [comment]
Are these applicable for this issue?
- [ ] Test suite(s) passing?
- [ ] Code coverage maximal?
- [ ] Changeset added?

**Comment by daneah** [comment]
@facelessfool The changeset is most applicable—I've posted a link for you over on the pull request. Once you add that, I'll trigger the CI and ensure the tests pass. As you suggest, we'd expect the tests to pass here, unless a test is expecting the broken spelling. Thanks for asking!
