### ISSUE TITLE
Pagination: Variant with page selector

### ISSUE THREAD

**Issue by ymouzakis** [ithaka/pharos#134]
**The problem**
I am always frustrated when looking through pages of **sorted** search results, and I can't select a page deeper into the results right away. This problem is even more annoying when the whole page reloads for each new page of search results.

**The solution**
Create a pagination component that allows for page selection. Now I can search through results more efficiently.

<img width="1527" alt="Screen Shot 2021-07-01 at 9 42 42 AM" src="https://user-images.githubusercontent.com/64924035/124134466-db838300-da50-11eb-84cd-107298bdf913.png">

**Alternatives considered**
I considered using the standard pagination component and trying to find a way to avoid page reloads when navigating between pages of results, but I do not think there is an easy way to avoid a reload. This is because the list of results is generated in Django.

**Additional information**
N/A

**Comment by daneah** [comment]
Closing this for now as the drivers haven't come back up in the intervening 2.5 years; this can be reopened or revamped if those drivers should come about later on.
