### ISSUE TITLE
Add pharos-spacing-10-x token

### ISSUE THREAD

**Issue by daneah** [ithaka/pharos#143]
**The problem**
In more editorial layouts, we want to be able to put just a big honking space between sections and whatnot.

**The solution**
Create a `pharos-spacing-10-x` token for use in application styles.

**Alternatives considered**
We can hard code `10rem` which is easy enough, but as with all things design token, we'd like to be able to change what `pharos-spacing-10-x` means some day and have things naturally update.

**Comment by Niznikr** [comment]
Resolved by #147
