### ISSUE TITLE
Automate last step of merging main into develop as part of our release workflow

### ISSUE THREAD

**Issue by Niznikr** [ithaka/pharos#149]
**The problem**
Currently after [making a release](https://github.com/ithaka/pharos/blob/develop/docs/development/conventions/creating-a-release.md#publishing-a-release) we need to manually merge `main` back into `develop` and push. We should automate the whole process to avoid the chance of forgetting to do this last step.

**The solution**

- Add a final step to the [release workflow](https://github.com/ithaka/pharos/blob/develop/.github/workflows/release.yml) that checks `if: steps.changesets.outputs.published == 'true'` and then proceeds to merge `main` into `develop` and push
- Update documentation

**Comment by daneah** [comment]
I know that GitHub has a tough time doing fast-forward merges when merging PRs in the UI, so my hope is we won't run into this same issue programmatically/with the Actions API.
