### ISSUE TITLE
Link: Add ability to render as a <button>

### ISSUE THREAD

**Issue by daneah** [ithaka/pharos#177]
**The problem**

Occasionally, it's useful to render something that looks like a link but is a `<button>` in the DOM.

**The solution**

Add a `variant="link"` that makes a Button look like a Link (including hover, focus, and so on), ideally by reusing exactly all the Link styles.

**Comment by Niznikr** [comment]
Based on how the button is implemented to [render as an anchor element](https://github.com/ithaka/pharos/blob/develop/packages/pharos/src/components/button/pharos-button.ts#L234) when a `href` attribute is present, it makes more sense to update the link component to follow a similar pattern. It can check for the absence of the `href` attribute to render as a `<button>` and have access to all the link variants/states in terms of styles.
