### ISSUE TITLE
Tooltip: Fixed strategy tooltips misaligned when browser chrome disappears on mobile

### ISSUE THREAD

**Issue by michael-iden** [ithaka/pharos#192]
**Expected behavior**
Tooltips always open directly adjacent to their associated element.

**Actual behavior**
Tooltips with the fixed positioning are misaligned from their associated element when the browser chrome disappears on mobile

**Steps to reproduce the issue**

1. Perform a [JSTOR search](https://www.jstor.org/action/doBasicSearch?Query=art&acc=on&wc=on&fc=off&group=none&refreqid=search%3A7484d1734f42c94961ab35b5e25aa93f) on a mobile browser. I was using Safari on iOS 14.7.1
2. Click "Cite" to open up the citation modal
3. Click "Copy" for one top citations (MLA, APA, Chicago)
3. See citation is misaligned if the browser chrome is not present. Opening the citation again with the chrome present has correctly aligned tooltips

**Screenshots or code**
Misaligned tooltip with chrome collapsed:
<img width="250" src="https://user-images.githubusercontent.com/13315416/128368761-a8c92d16-0cec-4fa1-a0f6-caff413dd336.png">

Aligned tooltip with chrome visible:
<img width="250" src="https://user-images.githubusercontent.com/13315416/128368818-f7e338d8-1b41-4dc0-957d-bc543ffac7d0.png">

**Pharos version**
10.5.1

**Your environment**

- OS: iOS
- Browser: Safari
- Version: 14.7.1

**Additional information**
We previously tried injecting the tooltips with the default strategy (without `strategy="fixed"`) and that had bigger issues.

**Comment by daneah** [comment]
Joined the discussion [here](https://github.com/popperjs/popper-core/issues/1121#issuecomment-932794689)

**Comment by daneah** [comment]
I will be interested to see if the next release containing #434 will remedy this.

**Comment by daneah** [comment]
[@ithaka/pharos@12.15.0](https://github.com/ithaka/pharos/releases/tag/%40ithaka%2Fpharos%4012.15.0) is likely to fix this; will close after confirmation from the team.
