### ISSUE TITLE
Pill/Chip: To represent an input, attribute, label or action

### ISSUE THREAD

**Issue by maddy531** [ithaka/pharos#218]
**The problem**
I need to represent a list of email addresses in an input field so that a user can add a single or multiple emails within the input field.

**The solution**
Creating a pill/chip component that standardized the look and behavior of this component. 

Here is the design we'd like to follow for this feature.

This is the starting state:
![Screen Shot 2021-09-13 at 9 05 10 AM](https://user-images.githubusercontent.com/10200622/133088915-fa0c3173-5b5e-4b86-8bd6-d36fe30ab302.png)

List state with valid pills:
![Screen Shot 2021-09-13 at 9 08 57 AM](https://user-images.githubusercontent.com/10200622/133089320-ebf8a465-dd9f-4394-8a9a-4e417bca20c2.png)

List state with pill error:
![Screen Shot 2021-09-13 at 9 05 27 AM](https://user-images.githubusercontent.com/10200622/133088922-51a7a24d-727e-4010-be24-7b5fc508568f.png)

Hover on pill error state:
![Screen Shot 2021-09-13 at 9 05 35 AM](https://user-images.githubusercontent.com/10200622/133088923-8bd55d71-d062-41f4-836b-4b696936e2b9.png)

**Alternatives considered**
I took a look at what Material Design does for similar use cases and I find that their [`chips component`](https://material.io/components/chips) is very similar to the behavior we're looking for.

**Comment by daneah** [comment]
Moved to #648
