### ISSUE TITLE
Footer: Content needs intrinsic padding

### ISSUE THREAD

**Issue by daneah** [ithaka/pharos#227]
**Expected behavior**

The footer content has an appropriate padding on all sides.

**Actual behavior**

Unless explicitly added by the consumer, the footer content only has padding on the top.

**Screenshots or code**

<img width="946" alt="Screen Shot 2021-09-28 at 21 21 54" src="https://user-images.githubusercontent.com/1808306/135186947-df0beec2-8de4-4273-8072-c256cc747d2a.png">

**Additional context**

Seems like `padding: var(--pharos-spacing-2-x) var(--pharos-spacing-1-x);` might be good:

<img width="980" alt="Screen Shot 2021-09-28 at 21 23 57" src="https://user-images.githubusercontent.com/1808306/135187116-453fe8de-9d10-4688-81dd-649adbc2498b.png">

**Comment by daneah** [comment]
@kelseycavitt Here's a suggestion if you'd like to give feedback or make the change 😄

**Comment by kelseycavitt** [comment]
Lol, I'd go with 2-x for that padding-bottom. But I'd also add a lil padding-top: spacing-one-half-x to .footer__row--bottom (where it's got those bottom links and the translate button)
