### ISSUE TITLE
DropdownMenuItem: MenuItem as link is missing rel attribute

### ISSUE THREAD

**Issue by michael-iden** [ithaka/pharos#279]
**Expected behavior**
Adding a `rel` attribute on the `pharos-dropdown-menu-item` is passed down to the underlying `a` tag

**Actual behavior**
`rel` attribute is omitted from the anchor tag inside the `pharos-dropdown-menu-item`

**Steps to reproduce the issue**

1. Add a standard dropdown to the page
2. Add a `rel="noopener"` attribute to one of the menu items
3. Inspect the DOM and see that it's not present

**Screenshots or code**
https://codesandbox.io/s/hungry-meninsky-e3ye8?file=/src/components/HelloWorld.vue

![image](https://user-images.githubusercontent.com/13315416/146014185-8db0303b-28dc-425a-ac4d-e50c6ba6a916.png)

**Pharos version**
11.1.0

**Your environment**

- OS: macOS
- Browser: Chrome
- Version: 96

**Additional information**
Add any additional notes or further context about the issue here.

**Comment by daneah** [comment]
This will likely need to be added as an optional property in [`PharosDropdownMenuItem`](https://github.com/ithaka/pharos/blob/develop/packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu-item.ts#L25) and conditionally rendered into [the underlying anchor tag](https://github.com/ithaka/pharos/blob/develop/packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu-item.ts#L164).
