### ISSUE TITLE
Tab: TypeError: can't access property "dataset", e is undefined

### ISSUE THREAD

**Issue by chrisjbrown** [ithaka/pharos#305]
**Expected behavior**
pharos-tabs, pharos-tab, and pharos-tab-panel initializes at the correct moment with no errors

**Actual behavior**
pharos-tabs is initializing and looking for a pharos-tab to select and not finding one. 
even though it's there, but maybe hasn't initialized yet?

**Steps to reproduce the issue**

1. https://codesandbox.io/s/snowy-firefly-2fxpy?file=/src/components/HelloWorld.vue
2. see error

**Screenshots or code**
![Screen Shot 2022-02-02 at 10 37 18 AM](https://user-images.githubusercontent.com/1250638/152192808-d1df26a1-ba9e-4fc1-9c0b-6f2fe8248b16.png)

**Pharos version**
11.2.1

**Your environment**
- OS: macOS
- Browser: Firefox
- Version: 97.0b9

**Additional information**
This could be related to the fact that we are dynamically registering these pharos components on vue component load

**Comment by daneah** [comment]
I suspect this is a race condition when the `PharosTabs` first updates, and the `PharosTab` items inside it haven't quite updated yet. That means they haven't added `data-pharos-component="PharosTab"` into the DOM—there's just the `<pharos-tab>` (or scoped version thereof). So not only does the `selected` query fail, but the `tabs` query fails too, ending with `selectedTab` being null, and `_queryPanelByTab` calling `tab.dataset` on a null tab.

Not really sure how best to fight this condition—we either need to ask `PharosTabs` to wait until all the `PharosTab` have loaded somehow, or use a different selector. The `data-panel-id` seems like something a `PharosTab` _should_ typically have, but it isn't a required property (or a property at all, in reality).

**Comment by daneah** [comment]
I don't believe we have existing use cases where `data-panel-id` is unspecified, but I don't believe making it required would resolve this issue. You'd still have the same race condition with a different selector, I believe.

**Comment by daneah** [comment]
Right, I was referring strictly to the `data-panel-id`...`data-tab-id` would be a different approach.

**Comment by daneah** [comment]
We may be able to solve this by ensuring slotted contents have completed rendering before fulfilling `updateComplete` by [overriding the `getUpdateComplete` method](https://lit.dev/docs/components/lifecycle/#getUpdateComplete).

**Comment by daneah** [comment]
This appears to have been fixed in Pharos 12.2.3 by #330. I can't quite tell what part of those changes would have had this positive impact, but I was able to switch between different Pharos versions in the CodeSandbox link you provided and narrow it down to that version.
