### ISSUE TITLE
Update on-background attribute for ease of use in Vue 3

### ISSUE THREAD

**Issue by michael-iden** [ithaka/pharos#307]
**Expected behavior**
When `on-background` attribute is applied to the button, the color scheme of the button is properly reflected

**Actual behavior**
`on-background` attribute is removed from the DOM, likely by Vue 3, possibly because it starts with `on*` and Vue 3 interprets that to be an event listener.

**Steps to reproduce the issue**

1. Create pharos button with `on-background` set on the element
2. Load up the app and see that the `on-background` is removed from the DOM
3. Button does not appear as we would expect

**Screenshots or code**
I tried making a codepen/codesandbox/stackblitz but each environment was having various issues. I'll keep trying to get a working example.

https://user-images.githubusercontent.com/13315416/153255838-d599f486-0e0d-4917-afa8-1e81b7e44038.mov

**Pharos version**
11.2.1

**Your environment**

- OS: macOS
- Browser: Chrome, Safari, Firefox
- Version: 98, 15.3, 92.0

**Additional information**
I couldn't find anything in the Vue3 docs where this was happening but the button works perfectly well in the same code on a Vue2 app.

**Comment by michael-iden** [comment]
@Niznikr It works! Thanks for the great suggestion! 
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/13315416/153419414-b68d3d7a-bee5-42fc-8112-5a9494564506.png">

**Comment by chrisjbrown** [comment]
@michael-iden is a fix still needed for this?

**Comment by michael-iden** [comment]
@chrisjbrown I think we still want to fix this and include #308 in the next set of breaking changes. Looks like Dane already tagged issue/PR with the v13 milestone and I can make sure it gets included

**Comment by Ivanok** [comment]
FWIW-- Using Nuxt 3 I couldn't get it working with `.onBackground` but instead with this: `:on-background.attr`

**Comment by mtorres3** [comment]
@michael-iden is this issue still reproducible or are we able to close it now? I'm not too familiar with Vue to test it locally 😅

**Comment by michael-iden** [comment]
@mtorres3 I think this is still technically an issue until pharos 14 is released

**Comment by daneah** [comment]
@michael-iden I much prefer to close issues as a fix for them is merged, regardless of whether that fix has yet been released—it becomes difficult to do bookkeeping otherwise.
