### ISSUE TITLE
Text Input/Input Group: Support multiple type="submit" elements in a single form

### ISSUE THREAD

**Issue by daneah** [ithaka/pharos#312]
**The problem**

When a form has multiple submit elements, which may impact how the form behaves, the current behavior that finds a submittable element in the form submits the first such element it finds. This is almost always okay, but breaks when there are multiple submit elements.

**The solution**

For now, to avoid a breaking change, add a prop to Text Input and Input Group(?) to allow bypassing of this behavior. This bypass should either cause it to do nothing instead, or possibly to defer to the form's submit handler instead of clicking the submit.

**Alternatives considered**

It would be possible to override the current Pharos behavior from the outside, but would involve listening for events on submit elements from afar and doesn't feel like the right approach.

**Comment by chrisjbrown** [comment]
I think this covers most of it. Don't know if it's worth clarifying. But the issue with the mfe header form is not that there are two submit buttons but that the click event handler is only meant to be triggered on an actual click on the button.

If the button is clicked. The click event handler is triggered. And because it is type=submit the form submit handler should also trigger automatically after.

If the enter key is pressed in the input box. The form submit handler should trigger. BUT the button click event trigger should NOT trigger.

**Comment by chrisjbrown** [comment]
I still wonder how detrimental this would be to just remove dispatching this "click" event.  

Just unsure how to test the repercussions this might have

**Comment by daneah** [comment]
Right, the proposal here is to make a non-breaking change first that makes the desired behavior _available_, so that it can be tried and ideally used in the place that first had a bug that drove adding the click event. In a major version, we can remove the click event if things go well, or at least switch to it being a non-default behavior if it proves necessary.

**Comment by daneah** [comment]
@chrisjbrown Firing a click event on the first submit button in tree order under the form is actually precisely [what the spec defines](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission) as the required behavior for implicit form submission.

I therefore think Pharos inputs behave according to the spec and should continue to do so. I see two ways forward to get the behavior you're after:

* Move the other submit buttons after the default submit button (search button) in the tree, while maintaining the positioning and styling they already have.
* Catch the keydown event on the input group or the subsequent fired click event, and implement the behavior you desire. The browser isn't smart enough to do this without you; it would exhibit the reported behavior even for a form build in native HTML5.

**Comment by daneah** [comment]
@chrisjbrown I opened a pull request for the part in question using the tree order change approach.
