### ISSUE TITLE
Button: Focus lost when text of button is changed on click

### ISSUE THREAD

**Issue by michael-iden** [ithaka/pharos#332]
**Expected behavior**
Focus is not lost when the contents of a button are updated

**Actual behavior**
Focus is lost and sent to the document body

**Steps to reproduce the issue**

1. Create pharos button
2. Add JS to change the text of the button on click (like a toggle)
3. Click button or tab to button and hit enter and see the focus is lost

**Screenshots or code**
Enter button clicked and focus is lost
https://user-images.githubusercontent.com/13315416/158630980-da4f441e-a689-4942-ba45-086b59e1b397.mov

```html
<pharos-button
       @click="handleToggleClicked"
>
    {{ buttonText }}
</pharos-button>
```

**Pharos version**
11.2.2

**Your environment**

- OS: macOS
- Browser: Chrome (not Firefox)
- Version: 99

**Additional information**
Can get around this by adding `<span>` around the text element

```html
<pharos-button
       @click="handleToggleClicked"
>
    <span>{{ buttonText }}</span>
</pharos-button>
```

**Comment by daneah** [comment]
@michael-iden I spent a bit of time finally getting a StackBlitz sandbox set up to reproduce Pharos issues more readily. I wasn't able to reproduce the behavior [here](https://stackblitz.com/edit/pharos-repro-332?file=src%252FApp.vue). Can you try creating a reproduction of the issue using [the sandbox](https://stackblitz.com/edit/pharos-repro-sandbox) as a starting place?

**Comment by daneah** [comment]
I can no longer reproduce this in the latest version of Chrome or Arc (also Chromium-based), and reconfirmed that this doesn't happen in Firefox or Safari.
