### ISSUE TITLE
Tab: First tab always gets selected disregarding the "selected" attribute

### ISSUE THREAD

**Issue by jialin-he** [ithaka/pharos#346]
**Expected behavior**

Second tab gets selected when I add `selected` to the second tab

```html
<pharos-tab
    id="second-tab"
    data-panel-id="second-tab-panel"
    selected
>
    Second tab
</pharos-tab>
```

<img width="368" alt="image" src="https://user-images.githubusercontent.com/38861633/168878201-0441ae62-7007-436a-8d2e-981e6f761df8.png">

**Actual behavior**
Both the first tab and second tab are selected (the first tab always gets selected).

<img width="317" alt="image" src="https://user-images.githubusercontent.com/38861633/168878253-67de8d54-44f5-4a46-9d5d-d46ead46e1b5.png">

**Steps to reproduce the issue**

1. Import `initComponents` in a bundle entry point, and use the Pharos tab in a component
2. Add `selected` attribute to the second tab
3. See that both tabs are selected

**Screenshots or code**
Add this code to the root component of a bundle, you can see the issue

```jsx
<pharos-tabs>
    <pharos-tab
        id="first-tab"
        data-panel-id="first-tab-panel"
    >
        First tab
    </pharos-tab>
    <pharos-tab
        id="second-tab"
        data-panel-id="second-panel"
        selected
    >
        Second tab
    </pharos-tab>
    <pharos-tab-panel
        id="first-tab-panel"
        slot="panel"
    >
        First
    </pharos-tab-panel>
    <pharos-tab-panel
        id="second-panel"
        slot="panel"
    >
        Second
    </pharos-tab-panel>
</pharos-tabs>
```

**Pharos version**
12.3.1

**Your environment**

- OS: macOS
- Browser: Chrome
- Version: 101

**Additional information**
Some weird behavior we have found.
If the tab is directly added to the index.html, it works.

It also works if you add another random tab without a corresponding tab panel. The code below works:

```jsx
<pharos-tabs>
    <pharos-tab
        id="first-tab"
        data-panel-id="first-tab-panel"
    >
        First tab
    </pharos-tab>
    <pharos-tab
        id="first-tab"
        data-panel-id="random-panel"
    >
        Another random tab
    </pharos-tab>
    <pharos-tab
        id="second-tab"
        data-panel-id="second-panel"
        selected
    >
        Second tab
    </pharos-tab>
    <pharos-tab-panel
        id="first-tab-panel"
        slot="panel"
    >
        First
    </pharos-tab-panel>
    <pharos-tab-panel
        id="second-panel"
        slot="panel"
    >
        Second
    </pharos-tab-panel>
</pharos-tabs>
```
<img width="496" alt="image" src="https://user-images.githubusercontent.com/38861633/168877467-ed07f755-032d-4c07-ae19-4929028d8931.png">

If we import the `initComponent` in the root component, it also works.

**Comment by chrisjbrown** [comment]
wanted to confirm this as we are using this on the `ImageSearchPage` search-results-vue component. but somehow when using computed values for `selected` it's working.

but just using a template. the outcome is as Jialin explains above.
https://stackblitz.com/edit/pharos-repro-sandbox-7fauj7?file=src%2Fmain.js,src%2FApp.vue

**Comment by daneah** [comment]
We may be able to solve this by ensuring slotted contents have completed rendering before fulfilling `updateComplete` by [overriding the `getUpdateComplete` method](https://lit.dev/docs/components/lifecycle/#getUpdateComplete).
