### ISSUE TITLE
DropdownMenuNav: Doesn't drop down when using a screen reader

### ISSUE THREAD

**Issue by fswlee** [ithaka/pharos#354]
**Expected behavior**
Dropdown menus should open without navigating to a new page

**Actual behavior**
Drop down menus in the main navigation don’t drop down. (Search, Browse, Tools). The only way to access these options using a screen reader is to click too open them in a new page - this causes confusion and extra work

**Steps to reproduce the issue**

1. (using JAWS) Go to JSTOR
2. tab to Search or Browse or Tools in the main nav
3. Press Enter or Space to open the menu. The site loads the linked page instead of opening the navigation. It doesn't open if I press the down arrow
4. On Chrome+VoiceOver I also can't consistently get the dropdown to work properly when i hit the spacebar or the down arrow. it tells me it's a visited link instead of "dropdown name, collapsed, menu item"

**Screenshots or code**
If applicable, add screenshots or code to help explain the issue.

**Pharos version**

Any

**Your environment**

- OS: Windows, mac
- Browser: Chrome

**Comment by chrisjbrown** [comment]
@daneah is this still an issue?
testing on storybook and jstor.org (firefox & chrome) seems to work as expected.

**Comment by daneah** [comment]
This may relate to #323, which we want to solve by removing some functionality.

**Comment by chrisjbrown** [comment]
I took a shot at a possible solution. but open to other suggestions
https://github.com/ithaka/pharos/pull/479#issue-1554143932

**Comment by daneah** [comment]
This will also include rendering the ARIA attributes onto the nested elements in the shadow DOM—a combination of #479 and forthcoming work on improving the story around ARIA rendering should help alleviate this issue, leaving open for documentative reasons atm.

**Comment by brentswisher** [comment]
@daneah and possibly @fswlee as well - Trying to figure out what needs to be done for the v14 release, will #479 close this issue when it is completed, or will there be additional work to do? If so, could you clarify a little what exactly needs to be done?

**Comment by daneah** [comment]
I believe #479 will resolve this.

**Comment by brentswisher** [comment]
Closed in #479, will be release in v14.0.0
