### ISSUE TITLE
Button: Add onBackground variant documentation on pharos.jstor.org

### ISSUE THREAD

**Issue by lorilundy711** [ithaka/pharos#383]
**Expected behavior**
Buttons on Dark Background section is unique and descriptive on https://pharos.jstor.org/components/button

**Actual behavior**
The Buttons on Dark Background section is a copy of the Disabled Button section. Does documentation exist for this section?

**Screenshots or code**
<img width="822" alt="Screen Shot 2022-07-26 at 10 47 20 AM" src="https://user-images.githubusercontent.com/80061918/181037607-3f36cba9-bc90-43b4-b26c-71070e33c399.png">

**Your environment**
MacOS Chrome

**Additional information**
If no documentation exists for this section, suggested copy is below:

Buttons on dark background
When a button is used on a darker background (e.g. black or marble-gray-20), use the on-background attribute. The four variants described above can all be used on dark backgrounds and follow the same guidelines.
`Primary Button` `Secondary Button`

**Comment by lorilundy711** [comment]
Updated visual for when on-background button styles are updated per new design direction:
![ButtonsOn-Background](https://user-images.githubusercontent.com/80061918/181038160-c17aabb8-b0eb-4f0a-9067-22d2abdd2a26.png)

**Comment by daneah** [comment]
@lorilundy711 I think the visual that's already present is correct, based on how primary buttons appear when `onBackground` is true. Can you confirm? I can get these docs updated pretty quickly pending resolution of this question.
