### ISSUE TITLE
Storybook: selecting multiple control options in composed Storybook causes story to cycle rapidly

### ISSUE THREAD

**Issue by drewgingerich** [ithaka/pharos#402]
**Expected behavior**
Selecting a variant in the Button Storybook changes the button variant then does nothing.

**Actual behavior**
Selecting a variant in the Button Storybook rapidly cycles through several variants.

**Steps to reproduce the issue**

1. Visit the [Base Button Story](https://pharos.jstor.org/storybook/?path=/story/webcomponents_components-button--base)
2. Navigate to the *Controls* panel
3. Select a different variant
4. Select a third variant

**Screenshots or code**

https://user-images.githubusercontent.com/15133892/188222529-595d8e26-1809-4ae7-a30a-44c524b11ae2.mov

**Comment by daneah** [comment]
Huh, that's an interesting one. I note that this only appears to happen in the composed Storybooks (both the web component and the React flavor)—this does not happen in the standalone Storybooks.

**Comment by daneah** [comment]
Further, this happens on other components for other controls. I experience the same on Modal when attempting to change the `size` control. I'd say this is a general problem.

**Comment by daneah** [comment]
No longer an issue in Storybook 7, it appears, after #543.
