### ISSUE TITLE
Pharos Tooltip Displays Under Pharos Modal

### ISSUE THREAD

**Issue by shoupeva-ithaka** [ithaka/pharos#458]
**Expected behavior**
Tooltip to display on hover inside the modal. 

**Actual behavior**
Tooltip is hidden behind the modal. 

**Steps to reproduce the issue**

1. Add a pharos modal to your project.
2. Add an element (that triggers the tooltip) and a pharos tooltip inside the modal.
3. Open the modal.
4. Hover the element and note that the tooltip does not show, but is present in the inspector and set as visible.

**Screenshots or code**

_tooltip is on the question icon next to the input group label_
![image](https://user-images.githubusercontent.com/112417900/203420469-32e44727-ba12-4818-a3e3-fd02276e4035.png)

_notice that the tooltip is indeed rendering on the screen_
![image](https://user-images.githubusercontent.com/112417900/203420539-b828ccfa-a773-4b5e-98a2-fc32daf7ff2c.png)

_notice that the tooltip has the "open" attribute on the element but is still not visible_
![image](https://user-images.githubusercontent.com/112417900/203420616-7c4e5c1b-5f24-4b93-848e-8945f20f5f22.png)

_notice the opacity is set to 1 after hovering_
![image](https://user-images.githubusercontent.com/112417900/203420867-5abfc33a-f134-4ef9-b983-2a8aad7ea89f.png)

_notice tooltip works when not in modal_
![image](https://user-images.githubusercontent.com/112417900/203421056-d909bf50-b465-4038-8180-22221745a488.png)

_modal z-index is 9000 and not overridable_
![image](https://user-images.githubusercontent.com/112417900/203421222-83375183-8056-48f9-b36c-65400ecc19a6.png)

_tooltip z-index is 140 and not overridable_
![image](https://user-images.githubusercontent.com/112417900/203421325-f31ff78e-394b-41c1-8e37-421f34f7019e.png)

**Pharos version**
^12.4.0

**Your environment**

- OS: macOS Montery v12.5.1
- Browser: Chrome v107.0.5304.110

**Comment by daneah** [comment]
@shoupeva-ithaka there exist examples of this working fine in the wild, so I suspect you should have a workaround available. It would be useful to understand the difference between those working examples and this broken one. One such working example is the **Copy** button within the **Cite** functionality on [the JSTOR search page](https://www.jstor.org/action/doBasicSearch?Query=pharos) as shown below:

<img width="706" alt="Screen Shot 2022-11-22 at 16 15 24" src="https://user-images.githubusercontent.com/1808306/203422557-0a1d6d3e-4fff-461b-8dca-a821e43c1f3d.png">

**Comment by shoupeva-ithaka** [comment]
Okay thank you for the reference, I will look into what they did for that!

**Comment by shoupeva-ithaka** [comment]
Ah, I guess the problem was that my tooltip was inside of a slot of a pharos component that was inside the modal. I moved the tooltip outside of the slot and it worked. Apologies for the "fake" issue 😬

**Comment by daneah** [comment]
@shoupeva-ithaka much appreciated either way. If the slotting proves to be a recurring issue we should certainly consider how to solve.
