### ISSUE TITLE
Tabs: Tab selection firing twice

### ISSUE THREAD

**Issue by michael-iden** [ithaka/pharos#462]
**Expected behavior**
On tab clicked, tab selected event fires a single time

**Actual behavior**
On tab click, tab selection event fires twice. For our specific purposes, this means a duplicate log event is emitted. 

**Steps to reproduce the issue**

See output of actions on events page within Pharos
https://pharos.jstor.org/storybook/?path=/story/webcomponents_components-tabs--events

**Screenshots or code**

https://user-images.githubusercontent.com/13315416/205705648-f405f3e2-7e95-4b16-b08c-49e298bb6a2c.mov

**Pharos version**
[v12.16.0](https://github.com/ithaka/pharos/releases/tag/%40ithaka%2Fpharos%4012.16.0)

**Your environment**

- OS: macOS, probably any
- Browser: Chrome, probably any 
- Version: 108, probably any

**Additional information**
Suspect the behavior was introduced in [v12.15.0](https://github.com/ithaka/pharos/releases/tag/%40ithaka%2Fpharos%4012.15.0)

**Comment by michael-iden** [comment]
Making a bit of a jump and assuming this introduced as part of 
https://github.com/ithaka/pharos/pull/442 to address https://github.com/ithaka/pharos/issues/220

I'm unsure the behavior from the initial pharos issue is desirable. I almost wrote up a a very similar story a few weeks ago to fire the change listener on programmatic update for checkboxes before realizing it was default behavior to not dispatch an event for setting a standard browser input checkbox to checked. This behavior feels similar enough to where we may want to keep the pattern. Looking for docs since I determined the checkbox behavior just by trying it manually by adding event listeners.

**Comment by chrisjbrown** [comment]
bit late to the party but...

I'm confused why is the event happening twice 😕 
is it that when the user clicks we dispatch `pharos-tab-selected` and set the property `selected` to `true`
which then triggers another dispatch of `pharos-tab-selected`?

**Comment by michael-iden** [comment]
Not sure I have a good answer on that either. There is a possibility we a plain ol' bug to be fixed with the event dispatching, but I also want to avoid diving too deep into event handling logic if we've added an anti-pattern in the first place. I'll check out the event logic and report back shortly

**Comment by michael-iden** [comment]
@chrisjbrown It looks like an interaction with the `pharos-tab-selected` we emit on a [tab](https://github.com/ithaka/pharos/blob/f02735b0f5237dc66e7c8823422bc132c83e58bd/packages/pharos/src/components/tabs/pharos-tab.ts#L62) itself, while also listening for the same `pharos-tab-selected` event on the [tabs container](https://github.com/ithaka/pharos/blob/f02735b0f5237dc66e7c8823422bc132c83e58bd/packages/pharos/src/components/tabs/pharos-tabs.ts#L52-L54). Could it be causing a cycle the browser realizes and breaks out of after 2 iterations?

**Comment by michael-iden** [comment]
Digging into the logic more, the event dispatching was also changed as part of #449 in addition to the aforementioned #442

**Comment by chrisjbrown** [comment]
looks like it's handling the click event... and then also running the updated event

Uploading Screenshare - 2023-01-06 3_45_19 PM.mp4…

**Comment by chrisjbrown** [comment]
could it be as simple as this to have the tab click event set itself as `selected` and let the update dispatch the event up?

https://github.com/ithaka/pharos/pull/468/files

**Comment by daneah** [comment]
@chrisjbrown from #449:

> The design flaw in tabs was letting each individual tab manage its own state when clicked. This created issues with state management centralization and reasoning. This change instead moves the job of state management to the Tabs component, which coordinates the individual Tab and TabPanel components it contains. This results in smoother management and, ultimately, a more correct implementation.

I don't feel good about having each individual tab perform state management that should be handled at the group-of-tabs level.

**Comment by chrisjbrown** [comment]
@daneah 🤔 i see. 
hmm really feels like we shouldn't have the `updated` event triggering another `_triggerSelectedEvent`
but then we're back to the problem of programmatically selecting a tab.

**Comment by chrisjbrown** [comment]
I wonder if we might move that logic to the `PharosTabs` component as well... maybe in the form of a prop like `selected-tab=0` where `0` is the index of the selected tab in the tab list. and when that is updated it updates the children accordingly

**Comment by chrisjbrown** [comment]
@michael-iden @daneah 
spent a bit more time on this today. 
I think this the closest I can get it to "almost" avoiding a breaking change.

what would break now is programmatic updates to `selected` on a `pharos-tab` would no longer trigger the click event updating the tabs.

https://github.com/ithaka/pharos/pull/468

**Comment by chrisjbrown** [comment]
double check 
@daneah was what was merged sufficient to fix this?

**Comment by daneah** [comment]
You may need to work that out with @michael-iden 😅

**Comment by michael-iden** [comment]
@daneah @chrisjbrown I don't think this has been officially released yet. There was a bit of an oops on Friday with a premature publishing of a pharos 13 version that didn't include everything we had tagged or staged with the next breaking release. But at last check, this fix was working when testing locally

**Comment by daneah** [comment]
I will close this issue, then, since we believe we have a forthcoming release that sufficiently fixes the issue.
