### ISSUE TITLE
Coachmark: Guide users through feature usage

### ISSUE THREAD

**Issue by shoupeva-ithaka** [ithaka/pharos#465]
**What is the use case for the component you're requesting?**
The form and function of the elements on an application can be difficult for users to decipher. Though we strive to simplify interaction with the applications we create, sometimes more context is needed for a user to understand them, or to undertsand parts of them. This difficulty is exacerbated when applications have a consistent stream of new users, update frequently, or have dynamic components that change during or between sessions.

Coachmarks, also referred to as popovers, display additional context to users to inform them of new or unique features, direct them in the right direction, or to assist them with an onboarding experience. They are frequently found in web or native applications as opposed to static sites (examples in next section). Here are some applicable use cases for the JSTOR platform...

- Highlight the workspace tab and how you can save items
- Highlight the multi-select feature on search results
- Provide a guided tour through the admin page
- Inform a search user why the "download" button is grayed out on a search result
- Inform a turnaway user that they are viewing a preview

Coachmarks can offer a more engaging experience for users and help fill gaps in their mental model of an application when used sparingly and correctly. Coachmarks are common, have a variety of use cases, and would be a strong edition to the Pharos opensource project.

**Landscape analysis**
Here are examples of coachmarks being used in the context of an application...

_Discord_
![image](https://user-images.githubusercontent.com/112417900/207106535-9f80e19e-f908-4286-85f6-9ed9c9613313.png)

_Mural_
![image](https://user-images.githubusercontent.com/112417900/207107604-7e6f05f0-7f46-41d6-8cba-948bfd66e54c.png)

_VS Code_
![image](https://user-images.githubusercontent.com/112417900/207106750-deeba23a-eabf-4907-a040-14d1c637d206.png)

_Science Direct_
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/112417900/207106969-7abed77f-5410-4cba-8f94-c192f685dc26.png">

Here are examples of coachmark components employed by other *popular* component libraries...

- [IBM Carbon Design System](https://carbondesignsystem.com/components/popover/usage/)
- [Material Design](https://mui.com/material-ui/react-popover/)
- [Chakra UI](https://chakra-ui.com/docs/components/popover/usage)
- [Bootstrap](https://getbootstrap.com/docs/4.0/components/popovers/)

**Additional considerations**
Most coachmarks are connected to a specific element or part of a page. However, there are examples of floating coachmarks that function similar to a notification or toast. Some questions and ideas...
- Does this justify having a separate component? or adding a feature to another component that already floats?
- Should we choose and stick with a single feature?
- Can we combine these features in a the same component?
	- If coachmark is tied to a component it mounts attached to that component with a caret. Otherwise it mounts in top-right corner without caret.

Below you will find more resources about the coachmark. The provided resources present a determintstic view on how the component should function and be used, but it is important to look to the future use cases of the component. The functionality of the component should be kept as agnostic as possible from any specific use case in order to provide flexability for when those use cases change or new ones are discovered (e.g. just because it is stated that interactive elements should not be used inside the coachmark does not mean we should prevent someone from doing so).

_Helpful Resources_
Reach out to PALS for more information.

**Comment by daneah** [comment]
Addressed in #608
