### ISSUE TITLE
Require descriptions for non-decorative icons without other visible descriptive text

### ISSUE THREAD

**Issue by daneah** [ithaka/pharos#467]
**The problem**

Some buttons have only an icon and trigger a tooltip on hover / focus. This may work for sighted users, but is not sufficient to convey meaning for those using assistive technologies.

**The solution**

When an icon appears in a non-decorative context, require that the developer provide a description. Note that this may require property drilling for things like Button whose API only allows the developer to reference an icon by name rather than providing any and all Icon properties directly.

**Alternatives considered**

We discussed the option of making all Icons require the description attribute, but there are valid use cases for decorative icons that don't require descriptive text. It isn't clear whether we intend or already have in practice used icons this way.

We could potentially require a description in all cases and have a `hidden` property or similar to hide decorative icons from being announced, thereby forcing the developer to opt explicitly for creating an icon without a description.

**Additional information**

Once an approach is finalized, we should provide guidance in the appropriate component documentation.

**Comment by daneah** [comment]
The work remaining here after #646 will be to remove the deprecated way of doing this using the `description` property.

**Comment by brentswisher** [comment]
Closed in #679
