### ISSUE TITLE
PharosToaster doesn't register PharosToast in the scope of its shadow root

### ISSUE THREAD

**Issue by drewgingerich** [ithaka/pharos#474]
**Expected behavior**
PharosToaster registers PharosToast in the scope of its shadow root, so that it can use the PharosToast component without needing the parent application to register PharosToast.

**Actual behavior**
PharosToast assumes that the PharosToast component has already been registered by the parent application using the same prefix as itself. [See these lines of the PharosToaster source code](https://github.com/ithaka/pharos/blob/develop/packages/pharos/src/components/toast/pharos-toaster.ts#L60-L61). If the parent application doesn't register PharosToast, then the PharosToast components PharosToaster creates will not have styling or logic since the browser doesn't recognize their custom HTML element tags.

**Additional information**
PharosToaster can use [@lit-labs/scoped-registry-mixin](https://github.com/lit/lit/tree/main/packages/labs/scoped-registry-mixin) to register PharosToast in the scope of its shadow root. PharosToast already uses this method to register PharosIcon and PharosToastButton. [See these lines of the PharosToast source code](https://github.com/ithaka/pharos/blob/develop/packages/pharos/src/components/toast/pharos-toast.ts#L41-L45).

**Comment by daneah** [comment]
To be released in v13
