### ISSUE TITLE
Site: Example Link renders as a button due to missing `href`

### ISSUE THREAD

**Issue by daneah** [ithaka/pharos#507]
**Expected behavior**

The basic example for the Link should probably render an anchor tag, per the principle of least surprise.

**Actual behavior**

The example renders as a button tag because it doesn't have an `href` value.

**Steps to reproduce the issue**

1. Visit the [component page](https://pharos.jstor.org/components/link)
2. Inspect the **I am a link** link example
3. Observe the `<button>` in its shadow DOM

**Screenshots or code**

![Screen Shot 2023-03-31 at 11 04 31 AM](https://user-images.githubusercontent.com/1808306/229246529-cce22a3d-b6f6-44a1-a7be-3206f221e038.png)

**Additional information**

An `href` value of `#` is probably appropriate.

**Comment by Pragyan14** [comment]
I want to work on this issue please assign me this issue.

**Comment by Yasir761** [comment]
@Pragyan14 currently I'm working on this
