### ISSUE TITLE
Modal: "Base" and "No footer" stories broken in Storybook

### ISSUE THREAD

**Issue by daneah** [ithaka/pharos#527]
**Expected behavior**

When I click the **Open modal** button, the modal opens

**Actual behavior**

When I click the **Open modal** button, nothing visually happens and I see the following error in the console:

```
caught TypeError: Cannot set properties of null (setting 'open')
```

**Steps to reproduce the issue**

1. Go to the story
2. Click the button

**Comment by HassanTanveer** [comment]
Hey, can you assign this issue to me?

**Comment by HassanTanveer** [comment]
I've started working on this, will create the PR soon.
