### ISSUE TITLE
Icon: Add icon for page scrolling mode and pagination mode

### ISSUE THREAD

**Issue by jialin-he** [ithaka/pharos#532]
**The problem**
We need an icon to show the viewer is in scrolling mode and another icon to show the viewer is in pagination mode.

<img width="390" alt="image" src="https://github.com/ithaka/pharos/assets/38861633/e4af4de7-3d9b-4cf1-bf6e-0d171901f534">

**The solution**
Add new icons to pharos.

**Comment by daneah** [comment]
Resolved in #533
