### ISSUE TITLE
PharosSidenavLink: External links don't open in a new tab

### ISSUE THREAD

**Issue by brentswisher** [ithaka/pharos#538]
**Expected behavior**
Based on the [Pharos documentation for the sidenav component](https://pharos.jstor.org/components/sidenav) when a link is set to external it should open in a new tab:

> The sidenav link sub-component has an external state which places the external icon at the end of the row and causes the link to be open in a new page/tab.

**Actual behavior**
External links open in the same tab

**Steps to reproduce the issue**
1. Create a side navigation component with an external link
2. Click the link
3. See that is does not open in a new tab

**Screenshots or code**
![PharosExternalLinkIssue](https://github.com/ithaka/pharos/assets/6653970/3db89501-5b62-4286-ae85-7653fb17a263)

**Pharos version**
12.19.2

**Your environment**

- OS: macOS
- Browser: Chrome
- Version: 113.0.5672.126

**Additional information**
- This appears to be the relevant section of code: https://github.com/ithaka/pharos/blob/c3dee79e090c92c5a42e6ebda662c9828ee2e7d2/packages/pharos/src/components/sidenav/pharos-sidenav-link.ts#L33

- Because it is also possible to manually pass the target through, we will need to check if that is set and likely have that override what would be set by external, so something like `external="true" target="_self"` would still open in the new tab

**Comment by brentswisher** [comment]
I'm happy to work up a PR to address this, but it might not be until early next month

**Comment by daneah** [comment]
Seems like the `pharos-link` maybe used to care about `external` and would self-manage the `target` and `rel` attributes, but now it's fairly geared toward acting like a "dumb" anchor tag that consumers need to add the values to themselves. We likely want the `sidenav-link` to render a `target="_blank"` and `rel="noopener [nofollow?]"` when `external` is specified.
