### ISSUE TITLE
Alert: Use icon-condensed for closeable alerts

### ISSUE THREAD

**Issue by daneah** [ithaka/pharos#548]
**The problem**

In closeable alerts with just a single line of text, the current close button is large enough that it ends up dictating the height of the alert. This causes the single line of text to have slightly more space below it than above it, which ends up looking like a mistaken attempt to vertically center the content (even though we're not explicitly vertically centering the content, here).

**The solution**

Use the `icon-condensed` property on the close button to make it ever-so-slightly smaller, collapsing it enough to restore the vertically-centered appearance of single-line text.

**Alternatives considered**

* Creating a new button variant with the icon the same size but with less padding—too much complexity.
* Explicitly vertically centering the text—probably easy enough to do, but not sure it's really the invariant we're going for here.

**Additional information**

Current:
<img width="676" alt="Screenshot 2023-06-20 at 17 13 31" src="https://github.com/ithaka/pharos/assets/1808306/53d8a8a5-bcb9-4d2e-a000-fe36375b5c55">

Desired:
<img width="674" alt="Screenshot 2023-06-20 at 17 14 17" src="https://github.com/ithaka/pharos/assets/1808306/13701f5b-8043-4236-959f-f947320afa2f">

**Comment by CYBWEBALI** [comment]
Can you assign this issue to me?

**Comment by CYBWEBALI** [comment]
After running yarn test it is failed and storybook is also not working.

Branch-Develop

**Comment by daneah** [comment]
@CYBWEBALI Sorry to hear that. Can you please provide more information? What isn't working? Is there a failure message? This information should let us help you more quickly!

**Comment by CYBWEBALI** [comment]
According to Contribution Guide, to run storybook cmd is:

`yarn storybook:wc:dev`

Command Output is:
![image](https://github.com/ithaka/pharos/assets/88965204/7a50f38f-fa57-4b08-82b2-8199c71cf04c)
![image](https://github.com/ithaka/pharos/assets/88965204/8d7d35b7-4d05-4314-ac6d-91685d9e7077)
![image](https://github.com/ithaka/pharos/assets/88965204/7ae99de8-5ddb-4b24-ab11-bd2bd50376f1)

**Comment by daneah** [comment]
@CYBWEBALI Thanks for the detail. Unfortunately I can't reproduce this on the head commit of `develop`. One difference I see is that you're using a Windows machine, which I'm not sure any of the team here is using for development. It ultimately looks like something is parsing the files incorrectly based on the copious string escapes in your output. It's quite possible something we're doing here is not Windows-compatible; I don't quite see that it is the part you highlighted at a glance, but possible. I won't be able to look deeper immediately, but if you make any headway in the meantime I'm sure we'd appreciate making sure things are working on Windows!
