### ISSUE TITLE
Heading: Console errors for invalid level attributes

### ISSUE THREAD

**Issue by michael-iden** [ithaka/pharos#549]
**Expected behavior**
Pharos headings can take in strings for levels

**Actual behavior**
Console errors are emitted because the string "1" does not match the valid numeric `1`

**Steps to reproduce the issue**

1. Use a pharos heading with a string for the `level` attribute

**Screenshots or code**
<img width="970" alt="image" src="https://github.com/ithaka/pharos/assets/13315416/4ef961fd-5047-4053-9d1a-d777d7f34b14">

**Pharos version**
Latest

**Your environment**

- OS: MacOS (likely any)
- Browser: Chrome (likely any)
- Version: 114

**Additional information**
Mostly just muddies up the console rather than causing any real user facing issues

**Comment by daneah** [comment]
@michael-iden I feel the appropriate action here is to use `:level="1"` instead of `level="1"`. Is that something you've tried?

**Comment by michael-iden** [comment]
That does work in the case of Vue app. But in the case of writing more vanilla HTML, it is more challenging?

**Comment by daneah** [comment]
@michael-iden a fair question, possible that it needs to be open to this case, something something `parseInt` something.

**Comment by daneah** [comment]
@michael-iden after some digging, I understand that, in non-framework use, Lit parses the DOM and [performs automatic conversions](https://lit.dev/docs/components/properties/#conversion-type) based on the `type` option of the `@property` decorator.

I then still believe that for framework use, consumers are indeed responsible for ensuring they pass a `Number` type using `:level="1"` or `level={1}`, and that for non-framework use, Lit has things covered.
