### ISSUE TITLE
Site: Pharos website links to storybook are broken

### ISSUE THREAD

**Issue by elisa-vargas** [ithaka/pharos#550]
**Expected behavior**
Navigating to the Pharos website and clicking on See in Storybook link opens the corresponding component's page in Storybook 

**Actual behavior**
Clicking on the "See in Storybook" opens Storybook but the following error is shown:

> "Couldn't find story matching 'components-tabs--base'.
> - Are you sure a story with that id exists?
> - Please check your stories field of your main.js config.
> - Also check the browser console and terminal for error messages."

Users can navigate the sidebar & open the correct link.

**Steps to reproduce the issue**

1. Navigate to https://pharos.jstor.org/components/tabs
2. Click on link "See in Storybook" (https://pharos.jstor.org/storybook/?path=/story/webcomponents_components-tabs--base) 
3. Error is shown on the resulting page

**Screenshots or code**
It seems that with the Storybook upgrade a name change has broken previously specified links:

Incorrect link address in "See in Storybook":
https://pharos.jstor.org/storybook/?path=/story/webcomponents_components-tabs--base 

Correct link in Storybook:
https://pharos.jstor.org/storybook/?path=/story/web-components_components-tabs--base

Every component page in Pharos probably needs to update and change from "/webcomponents_" to "/web-components_"

**Pharos version**
n/a

**Your environment**

- OS: macOS
- Browser: Chrome
- Version: 114.0.5735.198 

**Additional information**
Add any additional notes or further context about the issue here, including any known workarounds.

**Comment by daneah** [comment]
This likely broke when I upgraded Storybook in #543 / #546—we changed the composed Storybook name from `webcomponents` to `web-components` and the links use this in the URL—one line should fix it everywhere.
