### ISSUE TITLE
Toaster component throws errors when Toast is closed if a returnElements is not provided in the calling event

### ISSUE THREAD

**Issue by brentswisher** [ithaka/pharos#571]
**Expected behavior**
There would be no error if returnElements is provided because it defaults to an empty array

**Actual behavior**
The following error is emitted:

```javascript
pharos-toaster.js:71 Uncaught TypeError: returnElements is not iterable
    at PharosComponent._focusOnReturnElements (pharos-toaster.js:71:1)
    at PharosComponent._closeToast (pharos-toaster.js:84:1)
    at pharos-toast.js:101:1
    at debounce.js:10:1
```

**Steps to reproduce the issue**

1. Create a toast/toaster by emitting a custom event as detailed in the documentation without including a return element:
```javascript
const event = new CustomEvent("pharos-toast-open", {
        detail: {
            content: "Some problem has occurred",
            status: "error",
        },
    });
    document.dispatchEvent(event);
```
2. Trigger toast to show and then close
3. See error in browser console

**Screenshots or code**
I suspect [this section](https://github.com/ithaka/pharos/blob/develop/packages/pharos/src/components/toast/pharos-toaster.ts#L64) is always overwriting the default, even when it isn't undefined in the event.

```javascript
    const { content, status, id, indefinite, returnElements } = (<CustomEvent>event).detail;
    this.returnElements = returnElements;
```

**Pharos version**
12.19.2

**Your environment**
- OS: macOS Ventura
- Browser: Chrome 
- Version: 114.0.5735.248

**Comment by daneah** [comment]
Context: #503
