### ISSUE TITLE
Add new components to `initComponents` files

### ISSUE THREAD

**Issue by michael-iden** [ithaka/pharos#590]
**The problem**
I spent nearly an hour trying to debug my tests thinking there was a problem with the code, not realizing that I needed to add my new component definition to [this file to initialize components within the unit tests](https://github.com/ithaka/pharos/blob/44cc1a3ee1a494ac48af2371231b8de2f124c9da/packages/pharos/src/test/initComponents.ts).

**The solution**
New components created through the CLI are automatically added to `initComponents` files(s)

**Alternatives considered**
Add a direction to make this addition to the [CLI readme](https://github.com/ithaka/pharos/blob/730d381dd86fffe2543e37e2ef9a367611a997f1/packages/pharos-cli/README.md).

**Additional information**
We also need to add new component registration to the [storybook `initComponents`](https://github.com/ithaka/pharos/blob/4b833fab5e9bb65d0c03619f26cf1875ff16b400/.storybook/initComponents.js), but that felt more obviously necessary when I was visually testing compared to the failing unit tests.

**Comment by michael-iden** [comment]
@satya-achanta-venkata This seems reasonable to me. The concept and your source of inspiration for this change look like the right direction.

**Comment by daneah** [comment]
Addressed in #630
