### ISSUE TITLE
DropdownMenu: Light variant no longer has line rules between menu items

### ISSUE THREAD

**Issue by lorilundy711** [ithaka/pharos#597]
**Expected behavior**
Pharos dropdown menus with a light background have 1px marble-gray-80 border/line rules

**Actual behavior**
The light variant pharos dropdown doesn't include line rules between the menu items

**Steps to reproduce the issue**

1. Open a default pharos dropdown base variant

**Screenshots or code**
<img width="175" alt="Screenshot 2023-08-30 at 1 30 19 PM" src="https://github.com/ithaka/pharos/assets/80061918/78c204c3-744e-45bb-b421-5f8891a6c340">

**Pharos version**
Indicate which version of Pharos you are using.

**Your environment**

macOS
Chrome

**Additional information**
Add any additional notes or further context about the issue here, including any known workarounds.

**Comment by daneah** [comment]
Likely a result of #576
