### ISSUE TITLE
Site: Fix development environment

### ISSUE THREAD

**Issue by satya-achanta-venkata** [ithaka/pharos#632]
**Expected behavior**
Running `yarn site:develop` should run pharos site successfully locally

**Actual behavior**
Locally, I am seeing blank page and console errors after running `yarn site:develop`. (More in Additional Information)

**Steps to reproduce the issue**

1. On `develop` branch, run `yarn site:develop`
2. Gatsby service with pharos site docs, should be running on `http://localhost:8000`
3. Visiting, `http://localhost:8000` displaying blank page and having above mentioned console error (from **Actual Behavior**)

**Screenshots or code**
If applicable, add screenshots or code to help explain the issue.

**Pharos version**
`pharos site`: 5.13.4

**Your environment**

- OS: MacOS
- Browser: Chrome
- Version: 117.0.5938.149

**Additional information**

After running `yarn site:develop`, I see blank page with below console error:  
`Uncaught Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ../../node_modules/gatsby-plugin-mdx/loaders/mdx-components.js`. 

Also, I see this `warn` message during build process: `warn ../../node_modules/gatsby-plugin-mdx/wrap-root-element.js
Attempted import error: 'plugins' is not exported from './loaders/mdx-components' (imported as 'mdxPlugins').`

**Comment by daneah** [comment]
I believe this is because of the current version of `gatsby-plugin-mdx`, which we can resolve by:

* Upgrading to MDX 3 (this is involved, a bit)
* Upgrading to Gatsby 5 (I think this is ~free once we upgrade MDX)
* Upgrading `gatsby-plugin-mdx` to latest version

**Comment by satya-achanta-venkata** [comment]
@ithaka/pharos-maintainers 

versions: 

node v20.11.1

I am back at this issue and I am not seeing this happening anymore.  There is no console error anymore and i could see both `yarn site:serve` and `yarn site:develop` commands working as expected.  Can someone confirm you are seeing same behavior please ? 

However, pages such as Icon are currently broken and from console errors I understand its related to recent ally-label change we made in v14. I categorize this behavior as completely different issue.
