### ISSUE TITLE
Fix sidenav component documentation and function on pharos-site

### ISSUE THREAD

**Issue by shoupeva-ithaka** [ithaka/pharos#653]
**Description**
With the PharosSidenavButton being removed in v14.0.0, the Pharos site navigation will no longer function the same. The sidenav will no longer collapse on mobile. The sidenav documentation will be out of date and the code example will no longer be relevent.

**Comment by satya-achanta-venkata** [comment]
@shoupeva-ithaka  I see Chris Brown removed all the code that is related to PharosSidenavButton [here](https://github.com/ithaka/pharos/pull/478), so this issue can be closed.
