### ISSUE TITLE
Apply Elevation 5 to MODAL

### ISSUE THREAD

**Issue by nkamau** [ithaka/pharos#665]
**The problem**
Devs have to add elevation values to components after adding the component. We want to cut that extra step out. Instead of adding a component then adding the elevation effect after, the elevation effect will already be attached to the component. 

**The solution**
Please use these links to apply the value to the respective component:

MODAL uses Elevation 5.

Please use the value of "pharos-elevation-level-5" in storybook: https://pharos.jstor.org/storybook/?path=/story/react_styles-design-tokens--elevation

**Comment by brentswisher** [comment]
Closed with #681
