### ISSUE TITLE
Side navigation is not functioning as expected in the v14 release branch

### ISSUE THREAD

**Issue by brentswisher** [ithaka/pharos#673]
**Expected behavior**
The sidenav component is visible when it is expected to be.

**Actual behavior**
When viewing storybook on the v14 branch, the sidenav component is not displaying when it should be. It was also flagged by chromatic in a couple of builds: https://60919c26122bd50039b34644-xcjezwbxfi.chromatic.com/?path=/story/components-layout--one-column-with-sidenav&globals=viewport.width:1056

**Steps to reproduce the issue**

1. Run storybook on the v14 branch
2. Look at the stories which contain a sidenav component:
    1. Layouts > "with sidenav" stories
    2. Pages > Reports 
4. See that the sidenav is not displaying like it used to

**Screenshots or code**
<img width="1151" alt="Screenshot 2024-01-22 at 8 53 51 AM" src="https://github.com/ithaka/pharos/assets/6653970/1e65ba10-4d9e-48e7-b9cb-f4e4e24ce763">

**Pharos version**
v14 release branch

**Your environment**

- OS: macOS
- Browser: Chrome
- Version: 120.0.6099.216

**Additional information**
This seems to have happened around the time of #478. The components are mounted but are not being set to be visible.

**Comment by daneah** [comment]
Does this seem different than #653?

**Comment by brentswisher** [comment]
I _think_ so, as that is focused on the Pharos site and this is related to the storybook stories? @satya-achanta-venkata also took a look at that during our working session and thought it was already working as expected from what he could see.
