### ISSUE TITLE
Storybook: Upgrade to Storybook 8

### ISSUE THREAD

**Issue by daneah** [ithaka/pharos#710]
**The problem**
I want to be on recent and maintained versions of dependencies to ensure security and maintainability.

**The solution**
Upgrade to Storybook 8, possibly eagerly with the latest release candidate version.

**Additional information**

Known activities (started on `chore/update-storybook` branch):

- Run `yarn dlx storybook@next upgrade`
- Replace `ArgsTable` with `Controls` block on `docsPageConfig.jsx`
- Remove `@storybook/addon-styling`
- Remove `features: { storyStoreV7: true }`
- Rename `1.intro.docs.stories.mdx` and `2.changelog.docs.stories.mdx` to remove `.stories`
  - Update the `stories` property in the config to find these renamed files
  - Remove the `Pharos/` prefix from `<Meta title="...">` so they show up at the top
- Update `@storybook/client-api` imports to `@storybook/preview-api`

**Comment by brentswisher** [comment]
I think updating might solve some of our other storybook problems too, I'll take a shot at it
