### ISSUE TITLE
Pharos site mobile navigation menu has no way to close

### ISSUE THREAD

**Issue by shoupeva-ithaka** [ithaka/pharos#763]
**Expected behavior**
The side navigation is hidden by default, a menu icon button is present to open the side navigation, and when it is open it has a close button on mobile.

**Actual behavior**
The side navigation component on mobile is open by default and has no close button.

**Steps to reproduce the issue**

1. Go to https://pharos.jstor.org on a mobile device

**Screenshots or code**
<img width="426" alt="image" src="https://github.com/ithaka/pharos/assets/112417900/379d3c27-c483-442f-94c0-8c22605617a5">

**Pharos version**
N/A

**Your environment**

- OS: M1 Pro Mac – Sonoma 14.2.1
- Browser: Chrome / Safari

**Additional information**
The side navigation on mobile in the Safari browser also only expands to the navigation bar at the bottom (or the top as I believe that is a configurable setting). It can make for some wonky behavior. I wonder if it is also wise to have the side navigation height expand the entire height of the window instead of the viewport (then maybe an internal container element can only expand the height of the viewport for proper scroll behavior).

**Comment by daneah** [comment]
Likely introduced by #478 (see #417)
