### ISSUE TITLE
Add "Save & Close" icon

### ISSUE THREAD

**Issue by nkamau** [ithaka/pharos#788]
**What is the use case for the component you're requesting?**
Based on conversations with metadata librarians, this button is necessary for batch editing as opposed to regular save being best for individual. It makes their lives much, much easier. 

Icon:

![Save Close](https://github.com/user-attachments/assets/375584e9-946c-4fb0-82df-c02a9c573cf4)

Where it's located:

<img width="960" alt="Screenshot 2024-07-23 at 2 34 32 PM" src="https://github.com/user-attachments/assets/cfebd524-6cf8-4022-9806-d346bde74bd3">

**Additional considerations**
Alt-text: Save & close

**Comment by daneah** [comment]
@nkamau In dark mode in my browser I can see that you have some non-transparent fill:

<img width="36" alt="Screenshot 2024-07-23 at 20 52 51" src="https://github.com/user-attachments/assets/220600c4-b06d-4cc3-9fc3-8a9ed5e64a4f">

Is this how this should be?

**Comment by nkamau** [comment]
@daneah At that moment, yes, but I had a meeting this morning and was about to update it. I'm going to close this for a fresh ticket.
