### ISSUE TITLE
Add Upload icon

### ISSUE THREAD

**Issue by nkamau** [ithaka/pharos#789]
**What is the use case for the component you're requesting?**
We've been using the upload functionality across different ITHAKA platforms, but the icons are all different. Each has a different upload version. As Forum upgrades to Pharos, we're identifying places where contributing an icon could be beneficial for us and also other teams.

Icon:

![Upload](https://github.com/user-attachments/assets/bc733801-c10e-493b-9f5d-57eca74f1364)

Eg:

<img width="258" alt="Screenshot 2024-07-23 at 2 54 50 PM" src="https://github.com/user-attachments/assets/7f2e859c-50eb-49ff-bc9b-6fbc6597db74">

<img width="153" alt="Screenshot 2024-07-23 at 3 01 38 PM" src="https://github.com/user-attachments/assets/56c9b1ac-b7df-4604-9ab7-9113cacde245">

**Additional considerations**
Alt-title: Upload

**Comment by daneah** [comment]
@nkamau This icon is already present with the name `share`—perhaps we'd like to use that as-is, or to generalize the name so that it can handle both the concept of "share" and of "upload"?

**Comment by nkamau** [comment]
@daneah Thanks, Dane - Yeah, let's just use it...I'll tape the shoulders necessary to get this the same across our platforms.
