### ISSUE TITLE
Add "Save & Close" icon

### ISSUE THREAD

**Issue by nkamau** [ithaka/pharos#790]
**What is the use case for the component you're requesting?**
Based on conversations with metadata librarians, this button is necessary for batch editing as opposed to regular save being best for individual. It makes their lives much, much easier. 

Icon:
![save-and-close1](https://github.com/user-attachments/assets/ec5f6acb-8152-4828-a2e0-c51a56fbe8bc)

Where it's located:
<img width="801" alt="Screenshot 2024-07-24 at 10 33 00 AM" src="https://github.com/user-attachments/assets/1cd16705-5dd4-46f5-b1e3-d74c2faa4385">

**Additional considerations**
Alt-text: Save & close

**Comment by elisa-vargas** [comment]
@daneah Per discussion with Lori & Jo we've cleaned up the svg curves on this icon - should I submit a bug to get it updated or a new component request?

**Comment by daneah** [comment]
@elisa-vargas probably the "Feature request" option is best!
